### ISSUE TITLE
latex配置于vscode教程 | 300id’s blog

### ISSUE THREAD

**Issue by 300id** [300id/300id.github.io#5]
https://300id.github.io/blog/2023/10/12/latex-on-vscode/ 

 没啥说的

**Comment by doberse** [comment]
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 3c:ec:ef:78:07:6c brd ff:ff:ff:ff:ff:ff
    altname enp70s0f0
    inet 100.140.0.114/24 brd 100.140.0.255 scope global dynamic noprefixroute eno1
       valid_lft 37710sec preferred_lft 37710sec
    inet6 fe80::2be7:3dac:13e8:928b/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: eno2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 3c:ec:ef:78:07:6d brd ff:ff:ff:ff:ff:ff
    altname enp70s0f1
4: enxb03af2b6059f: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether b0:3a:f2:b6:05:9f brd ff:ff:ff:ff:ff:ff
    inet 110.120.0.166/24 brd 110.120.0.255 scope global noprefixroute enxb03af2b6059f
       valid_lft forever preferred_lft forever
    inet6 fe80::f280:99bb:a035:39c6/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

**Comment by doberse** [comment]
default via 100.140.0.1 dev eno1 
default via 100.140.0.1 dev eno1 proto dhcp metric 103 
100.140.0.0/24 dev eno1 proto kernel scope link src 100.140.0.114 metric 103 
110.120.0.0/24 via 100.140.0.1 dev eno1 
110.120.0.0/24 via 110.120.0.1 dev enxb03af2b6059f 
110.120.0.0/24 dev enxb03af2b6059f proto kernel scope link src 110.120.0.166 metric 104 
169.254.0.0/16 dev enxb03af2b6059f scope link metric 1000

**Comment by doberse** [comment]
内核 IP 路由表
目标            网关            子网掩码        标志  跃点   引用  使用 接口
0.0.0.0         100.140.0.1     0.0.0.0         UG    0      0        0 eno1
0.0.0.0         100.140.0.1     0.0.0.0         UG    103    0        0 eno1
100.140.0.0     0.0.0.0         255.255.255.0   U     103    0        0 eno1
110.120.0.0     100.140.0.1     255.255.255.0   UG    0      0        0 eno1
110.120.0.0     110.120.0.1     255.255.255.0   UG    0      0        0 enxb03af2b6059f
110.120.0.0     0.0.0.0         255.255.255.0   U     104    0        0 enxb03af2b6059f
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 enxb03af2b6059f

**Comment by doberse** [comment]
OpenSSH_8.9p1 Ubuntu-3ubuntu0.3, OpenSSL 3.0.2 15 Mar 2022
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolve_canonicalize: hostname 110.120.0.107 is address
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/root/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/root/.ssh/known_hosts2'
debug3: ssh_connect_direct: entering
debug1: Connecting to 110.120.0.107 [110.120.0.107] port 22.
debug3: set_sock_tos: set socket 3 IP_TOS 0x10
debug1: Connection established.
debug1: identity file /root/.ssh/id_rsa type -1
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa_sk type -1
debug1: identity file /root/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: identity file /root/.ssh/id_ed25519_sk type -1
debug1: identity file /root/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /root/.ssh/id_xmss type -1
debug1: identity file /root/.ssh/id_xmss-cert type -1
debug1: identity file /root/.ssh/id_dsa type -1
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.3
kex_exchange_identification: read: Connection reset by peer
Connection reset by 110.120.0.107 port 22

**Comment by 300id** [comment]
sudo apt-get update
sudo apt-get upgrade openssh-client openssh-server

**Comment by doberse** [comment]
root@lyz-Super-Server:/home/lyz# ssh -vvv root@110.120.0.107 -p 22
OpenSSH_8.9p1 Ubuntu-3ubuntu0.4, OpenSSL 3.0.2 15 Mar 2022
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolve_canonicalize: hostname 110.120.0.107 is address
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/root/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/root/.ssh/known_hosts2'
debug3: ssh_connect_direct: entering
debug1: Connecting to 110.120.0.107 [110.120.0.107] port 22.
debug3: set_sock_tos: set socket 3 IP_TOS 0x10
debug1: Connection established.
debug1: identity file /root/.ssh/id_rsa type -1
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa_sk type -1
debug1: identity file /root/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: identity file /root/.ssh/id_ed25519_sk type -1
debug1: identity file /root/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /root/.ssh/id_xmss type -1
debug1: identity file /root/.ssh/id_xmss-cert type -1
debug1: identity file /root/.ssh/id_dsa type -1
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.4
kex_exchange_identification: read: Connection reset by peer
Connection reset by 110.120.0.107 port 22

**Comment by 300id** [comment]
ssh -oKexAlgorithms=diffie-hellman-group14-sha1 -vvv root@110.120.0.107 -p 22

**Comment by 300id** [comment]
ssh -oGSSAPIAuthentication=no -vvv root@110.120.0.107 -p 22

**Comment by doberse** [comment]
[23:15:38.187] Spawned 1353637
[23:15:38.294] > local-server-1> Running ssh connection command: "-v -T -D 41747 -o ConnectTimeout=15 110.120.0.107"
[23:15:38.300] > local-server-1> Spawned ssh, pid=1353649
[23:15:38.305] stderr> OpenSSH_8.9p1 Ubuntu-3ubuntu0.4, OpenSSL 3.0.2 15 Mar 2022
[23:15:38.512] stderr> kex_exchange_identification: read: Connection reset by peer
[23:15:38.512] stderr> Connection reset by 110.120.0.107 port 22
[23:15:38.513] > local-server-1> ssh child died, shutting down
[23:15:38.519] Local server exit: 0
[23:15:38.519] Received install output: local-server-1> Running ssh connection command: "-v -T -D 41747 -o ConnectTimeout=15 110.120.0.107"
local-server-1> Spawned ssh, pid=1353649
OpenSSH_8.9p1 Ubuntu-3ubuntu0.4, OpenSSL 3.0.2 15 Mar 2022
kex_exchange_identification: read: Connection reset by peer
Connection reset by 110.120.0.107 port 22
local-server-1> ssh child died, shutting down

[23:15:38.521] Failed to parse remote port from server output
[23:15:38.524] Resolver error: Error: 
	at g.Create (/home/lyz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:642290)
	at t.handleInstallOutput (/home/lyz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:639656)
	at e (/home/lyz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:699953)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /home/lyz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:721822
	at async t.withShowDetailsEvent (/home/lyz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:725481)
	at async /home/lyz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:696658
	at async C (/home/lyz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:694709)
	at async t.resolveWithLocalServer (/home/lyz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:696198)
	at async I (/home/lyz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:719045)
	at async t.resolve (/home/lyz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:722852)
	at async /home/lyz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:906656
[23:15:38.533] ------

**Comment by doberse** [comment]
OpenSSH_8.9p1 Ubuntu-3ubuntu0.4, OpenSSL 3.0.2 15 Mar 2022

**Comment by 300id** [comment]
Host 主机B的IP地址
    KexAlgorithms +diffie-hellman-group1-sha1
    Ciphers +aes256-cbc

**Comment by doberse** [comment]
ssh: Could not resolve hostname 110.120.0.107:22: Name or service not known

**Comment by doberse** [comment]
kex_exchange_identification: read: Connection reset by peer
Connection reset by 110.120.0.107 port 22

**Comment by doberse** [comment]
/.ssh/known_hosts: No such file or directory
